---
title: "meningitis-backend"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{meningitis-backend}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(DataTriangulationStream2)
```

```{r}
chart_data <- dplyr::tbl(stream2_pool, "meningitis_coverage_cases_data")%>%
              dplyr::filter(Year %in% !!"2021" & Months %in% !!months_vector_util() & State %in% !!"Federal Government")%>%
              collect() %>%
              mutate(Months = lubridate::month(as.Date(str_c(Year, Months, 01,sep = "-"), "%Y-%b-%d"),
                                               label = T),across(c(Year,State ), as.factor))

    
chart_data 
```

```{r}

      plotmcac <- plot_ly(data = chart_data %>% arrange(Months))

      plotmcac <- plotmcac %>% add_trace(x = ~Months,
                                         y = ~`Meningitis Cases (CaseBased)`,
                                         type = 'bar',
                                         color =  I("#00a5cf"),
                                         name = 'Meningitis Cases (CaseBased) (Sormas)',
                                         #   marker = list(color = '#0000ff'),
                                         hovertemplate = paste('<b>Cases</b>: %{y:.0f}',
                                                               '<br><b style="text-align:left;">Month </b>: %{x}<br>'))

      #
      plotmcac <- plotmcac %>% add_trace(x = ~Months,
                                         y = ~`Meningitis Coverage (Dhis2)`,
                                         color = I("#004e64"),
                                         mode = 'lines+markers', type = 'scatter',
                                         line = list(shape = 'spline', linetype = I("solid")),
                                         marker = list(symbol = I("circle")),
                                         name = 'Meningitis Coverage (Dhis2)',
                                         hovertemplate = paste('<b>Coverage %</b>: %{y:.1f}',
                                                               '<br><b style="text-align:left;">Month </b>: %{x}<br>'),
                                         yaxis = 'y2')


plotmcac <- plotmcac %>% layout(
  # title = list(text = paste(paste0("State: ", picker_state_var()),paste0("Year: ", picker_year_var()),sep = "     "), 
  #              font = font_plot_title()),
                                      xaxis = list(tickfont = font_plot(),
                                                   title = "Month",
                                                   fixedrange = TRUE,
                                                   title= font_axis_title(),
                                                   ticks = "outside",
                                                   tickvals = ~Months,
                                                   showline = TRUE
                                      ),

                                      plot_bgcolor = measles_plot_bgcolor(),
                                      paper_bgcolor = measles_paper_bgcolor(),

                                      margin = plot_margin(),

                                      yaxis = list(side = 'left',
                                                   title = 'Number of cases',
                                                   showline = TRUE,
                                                   rangemode="tozero",
                                                   fixedrange = TRUE,
                                                   showgrid = FALSE,
                                                   zeroline = T,
                                                   ticks = "outside",
                                                   title = font_axis_title(), tickfont = font_plot()),
                                      yaxis2 = list(#range = c(0, 100),
                                        rangemode="tozero",
                                        fixedrange = TRUE,
                                        side = 'right',
                                        title = 'Coverage (%)',
                                        overlaying = "y",
                                        title = list(text = ""),
                                        showgrid = FALSE,
                                        ticks = "outside",
                                        zeroline = T,
                                        showline = TRUE,
                                        title = font_axis_title(),
                                        tickfont = font_plot()),



                                      legend = list(orientation = "h",   # show entries horizontally
                                                    xanchor = "center",  # use center of legend as anchor
                                                    x = 0.5,
                                                    y = -0.25),
                                      hoverlabel = list(font = font_hoverlabel()),
                                      font = font_plot())%>%
        config(displayModeBar = FALSE)
      # config(modeBarButtons = list(list("toImage", "resetScale2d", "zoomIn2d", "zoomOut2d")),
      #        displaylogo = FALSE, toImageButtonOptions = list(filename = "Chart 2- Confirmed measles cases, MCV 1 coverage.png"))

      plotmcac

    
```

### Age

```{r}

chart_data <- dplyr::tbl(stream2_pool, "meningitis_cases_age_combined")%>%
              dplyr::filter(Year %in% !!"2021" & Months %in% !!months_vector_util() & State %in% !!"Federal Government")%>%
              collect() %>% group_by(`Age group`) %>%
        summarise(across(c(Vaccinated,Unvaccinated,Unknown), ~ sum(.x, na.rm = TRUE))) %>%  ungroup() %>% dplyr::collect() %>%
        dplyr::mutate(`Age group` = 
                        factor(`Age group`,
                                labels = c("0-8 M", "9-23 M", "24-48 M", "5-9", "10-14", "15-19", "20-24", "25-29", "30-34", ">=35"),
                                levels = c("0-8 M", "9-23 M", "24-48 M", "5-9", "10-14", "15-19", "20-24", "25-29", "30-34", ">=35")))

      

```

```{r}
    p4 <- plot_ly(chart_data ,
                    x = ~`Age group`,
                    y = ~Unknown,
                    hovertemplate = paste('<b>Cases</b>: %{y:.0f}',
                                          '<br><b style="text-align:left;">Age group</b>: %{x}<br>'),
                    type = "bar",
                    color =  I("#004e64"),
                    name = "Unknown") %>%
        add_trace(y = ~Unvaccinated,
                  color = I("#00a5cf"),
                  hovertemplate = paste('<b>Cases</b>: %{y:.0f}',
                                        '<br><b style="text-align:left;">Age group</b>: %{x}<br>'),

                  name = "Unvaccinated") %>%
        add_trace(y = ~Vaccinated,
                  hovertemplate = paste('<b>Cases</b>: %{y:.0f}',
                                        '<br><b style="text-align:left;">Age group</b>: %{x}<br>'),

                  color = I("#edb952"),
                  name = "Vaccinated") %>%
        layout(
          #title = list(text = paste(paste0("State: ", picker_state_var()),paste0("Year: ", picker_year_var()), sep = "     "),
          #                  font = font_plot_title()),
               barmode = 'stack',
               xaxis = list(tickfont = font_plot(),
                            title = "Age group (M- months)",
                            fixedrange = TRUE,
                            title= font_axis_title(),
                            ticks = "outside",
                            showline = TRUE
               ),

               #width = "auto",
               # autosize = F,

               plot_bgcolor = measles_plot_bgcolor(),
               paper_bgcolor = measles_paper_bgcolor(),

               margin = plot_margin_one_side(),

               yaxis = list(side = 'left',
                            rangemode="tozero",
                            title = 'Number of cases',
                            showline = TRUE,
                            showgrid = FALSE,
                            fixedrange = TRUE,
                            zeroline = T,
                            ticks = "outside",
                            title = font_axis_title(),
                            tickfont = font_plot()),

               legend = list(orientation = "h",   # show entries horizontally
                             xanchor = "center",  # use center of legend as anchor
                             x = 0.5,
                             y = -0.25),
               hoverlabel = list(font = font_hoverlabel()),
               font = font_plot())%>%
        config(displayModeBar = FALSE)
      # config(modeBarButtons = list(list("toImage", "resetScale2d", "zoomIn2d", "zoomOut2d")),
      #                              displaylogo = FALSE, toImageButtonOptions = list(filename = "Chart 3- Age Group of Confirmed Measles Cases by Vaccination Status.png"))

      p4

    

```


## Map 

```{r}



```


