---
title: "wastage-rate"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{wastage-rate}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(DataTriangulationStream2)
```


```{r}
 chart_data <- dplyr::tbl(stream2_pool, "s6_combined")%>%
                dplyr::filter(Year %in% !!"2021" & Months %in% !!months_vector_util() & State %in% !!"Federal Government") %>%
                dplyr::collect() %>%
                dplyr::mutate(`Measles coverage` = `Measles coverage`*100,
                               Months = lubridate::month(as.Date(stringr::str_c(Year, Months, 01,sep = "-"), "%Y-%b-%d"),label = T),
                              dplyr::across(.col = c(Year,State ), as.factor),
                              `Measles Doses Wastage Rate` = 
                                ((`Measles Vaccine - Doses Opened (used)` - `Measles 1 given (administered)`)/
                                `Measles Vaccine - Doses Opened (used)`)*100
                              ) %>%
                dplyr::arrange(Months)
 chart_data
```

```{r}

      # measles_OB_OU_Received_1_combined_by_Year
      plotM <- plot_ly(data = chart_data %>%
                         arrange(Months))

      plotM <- plotM %>% add_trace(x = ~Months, y = ~`Measles coverage`,
                                   type = 'bar',
                                   color = I("#004e64"),
                                   hovertemplate = paste('<b>Coverage %</b>: %{y:.1f}',
                                                         '<br><b style="text-align:left;">Month </b>: %{x}<br>'),

                                   name = 'Measles Coverage',
                                   #marker = list(color = '#ffa500'),
                                   hoverinfo = "text",
                                   text = ~scales::number(`Measles coverage`,big.mark = ","))
      
      plotM <- plotM %>% add_trace(x = ~Months, y = ~`Measles Doses Wastage Rate`,
                                   type = 'scatter', mode = 'lines+markers',
                                   line = list(shape = 'spline', linetype = I("solid")),
                                   marker = list(symbol = I("circle")),
                                   color = I("#B37064"),
                                   hovertemplate = paste('<b>Measles Doses Wastage Rate %</b>: %{y:.1f}',
                                                         '<br><b style="text-align:left;">Month </b>: %{x}<br>'),

                                   name = 'Measles Doses Wastage Rate',
                                   #marker = list(color = '#ffa500'),
                                   hoverinfo = "text",
                                   text = ~scales::number(`Measles Doses Wastage Rate`,big.mark = ","))

      plotM <- plotM %>% add_trace(x = ~Months,
                                   y = ~`Measles Vaccine - Doses Opened (used)`,
                                   color = I("#00a5cf"),
                                   type = 'scatter', mode = 'lines+markers',
                                   line = list(shape = 'spline', linetype = I("solid")),
                                   marker = list(symbol = I("circle")),
                                   name = 'Measles Vaccine - Doses Opened (Used)',
                                   yaxis = 'y2',
                                   hovertemplate = paste('<b>Number</b>: %{y:.0f}',
                                                         '<br><b style="text-align:left;">Month </b>: %{x}<br>'),
                                   # line = list(color = '#0000ff'),
                                   hoverinfo = "text",
                                   text = ~scales::number(`Measles Vaccine - Doses Opened (used)`, big.mark = ","))

      plotM <- plotM %>% add_trace(x = ~Months,
                                   y = ~`Measles 1 given (administered)`,
                                   color =  I("#94D2BD"),
                                   type = 'scatter',
                                   mode = 'lines+markers',
                                   line = list(shape = 'spline', linetype = I("solid")),
                                   marker = list(symbol = I("circle")),
                                   name = 'MCV 1 (administered)',
                                   yaxis = 'y2',
                                   hovertemplate = paste('<b>Number</b>: %{y:.1f}',
                                                         '<br><b style="text-align:left;">Month </b>: %{x}<br>')
                                   # line = list(color = '#008000'),
      )

      plotM <- plotM %>% add_trace(x = ~Months,
                                   y = ~`Measles Doses Available (Opening Balance+Received)`,
                                   color = I("#edb952"),
                                   type = 'scatter',
                                   mode = 'lines+markers',
                                   line = list(shape = 'spline', linetype = I("solid")),
                                   marker = list(symbol = I("circle")),
                                   name = 'Measles Doses Available (Opening Balance+Received)',
                                   yaxis = 'y2',
                                   hovertemplate = paste('<b>Number</b>: %{y:.0f}',
                                                         '<br><b style="text-align:left;">Month </b>: %{x}<br>'))

      plotM <- plotM %>% layout(
        #title = list(text = paste(paste0("State: ", picker_state_var()),paste0("Year: ", picker_year_var()), sep = "     "),
         #                                     font = font_plot_title()),
                                 xaxis = list(tickfont = font_plot(),
                                              title = "Month",
                                              title= font_axis_title(),
                                              fixedrange = TRUE,
                                              ticks = "outside",
                                              showline = TRUE,
                                              tickvals = ~Months),

                                 #width = "auto",
                                 # autosize = F,

                                 plot_bgcolor = measles_plot_bgcolor(),
                                 paper_bgcolor = measles_paper_bgcolor(),

                                 margin = plot_margin(),


                                 yaxis = list(#range = c(0, 100),
                                   side = 'right',
                                   title = '(%)',
                                   showline = TRUE,
                                   showgrid = FALSE,
                                   fixedrange = TRUE,
                                   zeroline = T,
                                   ticks = "outside",
                                   title = font_axis_title(), tickfont = font_plot()),
                                 yaxis2 = list(side = 'left',
                                               overlaying = "y",
                                               rangemode="tozero",
                                               title = 'Vaccine Stock (number in doses)',
                                               showgrid = FALSE,
                                               ticks = "outside",
                                               zeroline = FALSE,
                                               fixedrange = TRUE,
                                               showline = TRUE,
                                               title = font_axis_title(), tickfont = font_plot()),

                                 legend = list(orientation = "h",   # show entries horizontally
                                               xanchor = "center",  # use center of legend as anchor
                                               x = 0.5,
                                               y = -0.25),
                                 hoverlabel = list(font = font_hoverlabel()),
                                 font = font_plot())%>%
        config(displayModeBar = FALSE)

      # config(modeBarButtons = list(list("toImage", "resetScale2d", "zoomIn2d", "zoomOut2d")),
      #        displaylogo = FALSE, toImageButtonOptions = list(filename = "Chart 5- Measles Vaccine Stock Analysis & Measles Coverage.png"))
      plotM

    
```

