---
title: "year-filter"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{year-filter}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(DataTriangulationStream2)
```


```{r}
chart_data <- dplyr::tbl(connection, "s3_combined")%>%
        dplyr::filter(Year %in% !!c("2019","2020","2021", "2022") & Months %in% !!months_vector_util() & State %in% !!"Federal Government")%>%
        collect() %>%
        mutate(Months = as.Date(str_c(Year, Months, 01,sep = "-"), "%Y-%b-%d"),
               Month = str_c(Month, Year, sep = "-"),
               across(c(Year,State ), as.factor))


chart_data
```


```{r}

      plotmcac <- plot_ly(data = chart_data %>% arrange(Months))

      plotmcac <- plotmcac %>% add_trace(x = ~Months, y = ~`Measles Cases (CaseBased)`,
                                         type = 'bar',
                                         color =  I("#00a5cf"),
                                         name = 'Measles Cases (CaseBased) (Sormas)',
                                         #   marker = list(color = '#0000ff'),
                                         hovertemplate = paste('<b>Cases</b>: %{y:.0f}',
                                                               '<br><b style="text-align:left;">Month </b>: %{x}<br>'))

      #
      plotmcac <- plotmcac %>% add_trace(x = ~Months,
                                         y = ~`Measles Dose Coverage (Admin)`,
                                         color = I("#004e64"),
                                         mode = 'lines+markers', type = 'scatter',
                                         line = list(shape = 'spline', linetype = I("solid")),
                                         marker = list(symbol = I("circle")),
                                         name = 'Measles Dose Coverage (Admin) (Dhis2)',
                                         hovertemplate = paste('<b>Coverage %</b>: %{y:.1f}',
                                                               '<br><b style="text-align:left;">Month </b>: %{x}<br>'),
                                         yaxis = 'y2')

      plotmcac <- plotmcac %>% add_trace(x = ~Months,
                                         y = ~`Measles Coverage (Alt Denominator)`,
                                         color = I("#edb952"),
                                         line = list(shape = 'spline', linetype = I("solid")),
                                         marker = list(symbol = I("circle")),
                                         mode = 'lines+markers', type = 'scatter',
                                         hovertemplate = paste('<b>Coverage %</b>: %{y:.1f}',
                                                               '<br><b style="text-align:left;">Month </b>: %{x}<br>'),
                                         name = 'Measles Coverage (Alt Denominator) (Dhis2)',
                                         yaxis = 'y2')

      plotmcac <- plotmcac %>% layout(
        #title = list(text = paste(paste0("State: ", picker_state_var()),paste0("Year: ", picker_year_var()), sep = "     "),
          #                                         font = font_plot_title()),
                                      xaxis = list(tickfont = font_plot(),
                                                   title = "Month",
                                                   fixedrange = TRUE,
                                                   title= font_axis_title(),
                                                   ticks = "outside",
                                                   tickvals = ~ Months,
                                                   showline = TRUE,
                                                   dtick = "M1", 
                                                   tickformat="%b-%Y"
                                                   
                                      ),

                                      plot_bgcolor = measles_plot_bgcolor(),
                                      paper_bgcolor = measles_paper_bgcolor(),

                                      margin = plot_margin(),

                                      yaxis = list(side = 'left',
                                                   title = 'Number of cases',
                                                   showline = TRUE,
                                                   rangemode="tozero",
                                                   fixedrange = TRUE,
                                                   showgrid = FALSE,
                                                   zeroline = T,
                                                   ticks = "outside",
                                                   title = font_axis_title(), tickfont = font_plot()),
                                      yaxis2 = list(#range = c(0, 100),
                                        rangemode="tozero",
                                        fixedrange = TRUE,
                                        side = 'right',
                                        title = 'Coverage (%)',
                                        overlaying = "y",
                                        title = list(text = ""),
                                        showgrid = FALSE,
                                        ticks = "outside",
                                        zeroline = T,
                                        showline = TRUE,
                                        title = font_axis_title(),
                                        tickfont = font_plot()),



                                      legend = list(orientation = "h",   # show entries horizontally
                                                    xanchor = "center",  # use center of legend as anchor
                                                    x = 0.5,
                                                    y = -0.25),
                                      hoverlabel = list(font = font_hoverlabel()),
                                      font = font_plot())%>%
        config(displayModeBar = FALSE)
      # config(modeBarButtons = list(list("toImage", "resetScale2d", "zoomIn2d", "zoomOut2d")),
      #        displaylogo = FALSE, toImageButtonOptions = list(filename = "Chart 2- Confirmed measles cases, MCV 1 coverage.png"))

      plotmcac


```

