default:
  development_stream2:
    user: !expr Sys.getenv("DBUSER")
    password: !expr Sys.getenv("DBPWD")
    host: !expr Sys.getenv("DBHOST")
    port: 3306
    database: !expr Sys.getenv("database_name")
